Entity/MessageInterface.php
<?php
/**
 * Created by PhpStorm.
 * User: andrew
 * Date: 01.04.14
 * Time: 13:25
 * Author: Kluev Andrew
 * Contact: Kluev.Andrew@gmail.com
 */
namespace SeoSA\FeedbackBundle\Entity;

/**
 * Interface SeoSA\FeedbackBundle\Entity\MessageInterface
 */
interface MessageInterface
{
    /**
     * @return int
     */
    public function getId();

    /**
     * @param string $body
     *
     * @return $this
     */
    public function setBody($body);

    /**
     * @return string
     */
    public function getBody();

    /**
     * @param string $title
     *
     * @return $this
     */
    public function setTitle($title);

    /**
     * @return string
     */
    public function getTitle();

    /**
     * @param boolean $boolean
     *
     * @return $this
     */
    public function setRead($boolean);

    /**
     * @return boolean
     */
    public function isRead();

    /**
     * @return \DateTime
     */
    public function getCreatedAt();

    /**
     * @param \DateTime $data
     *
     * @return $this
     */
    public function setCreatedAt(\DateTime $data);

    /**
     * @param string $permalink
     *
     * @return $this
     */
    public function setPermalink($permalink);

    /**
     * @return string
     */
    public function getPermalink();
}
 

Form/MessageType.php
<?php
/**
 * Created by PhpStorm.
 * User: andrew
 * Date: 01.04.14
 * Time: 16:05
 * Author: Kluev Andrew
 * Contact: Kluev.Andrew@gmail.com
 */
namespace SeoSA\FeedbackBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

/**
 * Class SeoSA\FeedbackBundle\Form\MessageType
 */
class MessageType extends AbstractType
{
    /**
     * @var string
     */
    protected $class;

    /**
     * Constructor
     *
     * @param string $class
     */
    public function __construct($class)
    {
        $this->class = (string) $class;
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'seo_sa_feedback_message';
    }

    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return 'form';
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('title');
        $builder->add('body');
        $builder->add('permalink', 'hidden');
        $builder->add('submit', 'submit');
    }

    /**
     * {@inheritdoc}
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => $this->class
            ]
        );
    }
}
 

Resources/views/SonataAdmin/list_url.html.twig
{#
 # Created by PhpStorm.
 # User: andrew
 # Date: 02.04.14
 # Time: 9:48
 # Author: Kluev Andrew
 # Contact: Kluev.Andrew@gmail.com
 #}
{% extends admin.getTemplate('base_list_field') %}

{% block field %}
    {% spaceless %}
        {% if value is empty %}
            &nbsp;
        {% else %}
            {% if field_description.options.url is defined %}
                {# target url is string #}
                {% set url_address = field_description.options.url %}
            {% elseif field_description.options.route is defined and field_description.options.route.name not in ['edit', 'show'] %}
                {# target url is Symfony route #}
                {% set parameters = field_description.options.route.parameters|default([]) %}

                {# route with paramter related to object ID #}
                {% if field_description.options.route.identifier_parameter_name is defined %}
                    {% set parameters = parameters|merge({(field_description.options.route.identifier_parameter_name):(admin.normalizedidentifier(object))}) %}
                {% endif %}

                {% if field_description.options.route.absolute|default(false) %}
                    {% set url_address = url(field_description.options.route.name, parameters) %}
                {% else %}
                    {% set url_address = path(field_description.options.route.name, parameters) %}
                {% endif %}
            {% else %}
                {# value is url #}
                {% set url_address = value %}
            {% endif %}

            {% if field_description.options.hide_protocol|default(false) %}
                {% set value = value|replace({'http://': '', 'https://': ''}) %}
            {% endif %}

            <a target="_blank" href="{{ url_address }}">{{ value }}</a>
        {% endif %}
    {% endspaceless %}
{% endblock %}

Resources/views/SonataAdmin/show_mark_as_read.html.twig
{#
 # Created by PhpStorm.
 # User: andrew
 # Date: 02.04.14
 # Time: 9:57
 # Author: Kluev Andrew
 # Contact: Kluev.Andrew@gmail.com
 #}
{% trans_default_domain 'SeoSAFeedbackBundle' %}

{% spaceless %}
    <td colspan="2" style="text-align: center">
        {% if not object.isRead %}
                <form action="{{ path('seo_sa_feedback_patch_message_read', {'messageId': object.id }) }}" method="POST">
                    <input type="hidden" name="_method" value="PATCH"/>
                    <input type="hidden" name="state" value="1"/>
                    <input type="submit" name="submit" class="btn btn-primary" value="{{ 'Mark as read'|trans }}"/>
                </form>
        {% else %}
            <form action="{{ path('seo_sa_feedback_patch_message_read', {'messageId': object.id }) }}" method="POST">
                <input type="hidden" name="_method" value="PATCH"/>
                <input type="hidden" name="state" value="0"/>
                <input type="submit" name="submit" class="btn btn-warning" value="{{ 'Mark as not read'|trans }}"/>
            </form>
        {% endif %}
    </td>
{% endspaceless %}

Resources/views/SonataAdmin/show_url.html.twig
{#
 # Created by PhpStorm.
 # User: andrew
 # Date: 02.04.14
 # Time: 9:48
 # Author: Kluev Andrew
 # Contact: Kluev.Andrew@gmail.com
 #}
{% extends 'SonataAdminBundle:CRUD:base_show_field.html.twig' %}

{% block field %}
    {% spaceless %}
        {% if value is empty %}
            &nbsp;
        {% else %}
            {% if field_description.options.url is defined %}
                {# target url is string #}
                {% set url_address = field_description.options.url %}
            {% elseif field_description.options.route is defined and field_description.options.route.name not in ['edit', 'show'] %}
                {# target url is Symfony route #}
                {% set parameters = field_description.options.route.parameters|default([]) %}

                {# route with paramter related to object ID #}
                {% if field_description.options.route.identifier_parameter_name is defined %}
                    {% set parameters = parameters|merge({(field_description.options.route.identifier_parameter_name):(admin.normalizedidentifier(object))}) %}
                {% endif %}

                {% if field_description.options.route.absolute|default(false) %}
                    {% set url_address = url(field_description.options.route.name, parameters) %}
                {% else %}
                    {% set url_address = path(field_description.options.route.name, parameters) %}
                {% endif %}
            {% else %}
                {# value is url #}
                {% set url_address = value %}
            {% endif %}

            {% if field_description.options.hide_protocol|default(false) %}
                {% set value = value|replace({'http://': '', 'https://': ''}) %}
            {% endif %}

            <a href="{{ url_address }}">
                {%- if field_description.options.safe -%}
                    {{- value|raw -}}
                {%- else -%}
                    {{- value -}}
                {%- endif -%}
            </a>
        {% endif %}
    {% endspaceless %}
{% endblock %}