Entity/Message.php
<?php
/**
 * Created by PhpStorm.
 * User: andrew
 * Date: 01.04.14
 * Time: 13:25
 * Author: Kluev Andrew
 * Contact: Kluev.Andrew@gmail.com
 */
namespace SeoSA\FeedbackBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class SeoSA\FeedbackBundle\Entity\Message
 *
 * @ORM\MappedSuperclass
 */
class Message implements MessageInterface
{

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime")
     */
    protected $createdAt;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     * @Assert\NotBlank(
     *      message="Specify a title"
     * )
     */
    protected $title;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     */
    protected $permalink;


    /**
     * @var string
     *
     * @ORM\Column(type="text")
     * @Assert\NotBlank(
     *      message="Specify a message"
     * )
     */
    protected $body;

    /**
     * Column name "is_read" because "read" is reserved mysql keyword
     *
     * @var bool
     *
     * @ORM\Column(name="is_read", type="boolean")
     */
    protected $read = false;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->setCreatedAt(new \DateTime());
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->id;
    }


    /**
     * {@inheritdoc}
     */
    public function setBody($body)
    {
        $this->body = (string) $body;

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     *{@inheritdoc}
     */
    public function setRead($boolean)
    {
        $this->read = (bool) $boolean;

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function isRead()
    {
        return (bool) $this->read;
    }

    /**
     * {@inheritdoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * {@inheritdoc}
     */
    public function setTitle($title)
    {
        $this->title = (string) $title;

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * {@inheritdoc}
     */
    public function setPermalink($permalink)
    {
        $this->permalink = $permalink;

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function getPermalink()
    {
        return $this->permalink;
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return 'Message #' . $this->getId();
    }
}
 

Entity/MessageInterface.php
<?php
/**
 * Created by PhpStorm.
 * User: andrew
 * Date: 01.04.14
 * Time: 13:25
 * Author: Kluev Andrew
 * Contact: Kluev.Andrew@gmail.com
 */
namespace SeoSA\FeedbackBundle\Entity;

/**
 * Interface SeoSA\FeedbackBundle\Entity\MessageInterface
 */
interface MessageInterface
{
    /**
     * @return int
     */
    public function getId();

    /**
     * @param string $body
     *
     * @return $this
     */
    public function setBody($body);

    /**
     * @return string
     */
    public function getBody();

    /**
     * @param string $title
     *
     * @return $this
     */
    public function setTitle($title);

    /**
     * @return string
     */
    public function getTitle();

    /**
     * @param boolean $boolean
     *
     * @return $this
     */
    public function setRead($boolean);

    /**
     * @return boolean
     */
    public function isRead();

    /**
     * @return \DateTime
     */
    public function getCreatedAt();

    /**
     * @param \DateTime $data
     *
     * @return $this
     */
    public function setCreatedAt(\DateTime $data);

    /**
     * @param string $permalink
     *
     * @return $this
     */
    public function setPermalink($permalink);

    /**
     * @return string
     */
    public function getPermalink();
}
 

Entity/SignedMessageInterface.php
<?php
/**
 * Created by PhpStorm.
 * User: andrew
 * Date: 01.04.14
 * Time: 13:29
 * Author: Kluev Andrew
 * Contact: Kluev.Andrew@gmail.com
 */
namespace SeoSA\FeedbackBundle\Entity;

use Symfony\Component\Security\Core\User\UserInterface;

/**
 * Interface SeoSA\FeedbackBundle\Entity\SignedMessageInterface
 */
interface SignedMessageInterface extends MessageInterface
{
    /**
     * @param UserInterface|null $user
     *
     * @return $this
     */
    public function setAuthor(UserInterface $user = null);

    /**
     * @return UserInterface|null
     */
    public function getAuthor();
}
 

Form/MessageType.php
<?php
/**
 * Created by PhpStorm.
 * User: andrew
 * Date: 01.04.14
 * Time: 16:05
 * Author: Kluev Andrew
 * Contact: Kluev.Andrew@gmail.com
 */
namespace SeoSA\FeedbackBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

/**
 * Class SeoSA\FeedbackBundle\Form\MessageType
 */
class MessageType extends AbstractType
{
    /**
     * @var string
     */
    protected $class;

    /**
     * Constructor
     *
     * @param string $class
     */
    public function __construct($class)
    {
        $this->class = (string) $class;
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'seo_sa_feedback_message';
    }

    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return 'form';
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('title');
        $builder->add('body');
        $builder->add('permalink', 'hidden');
        $builder->add('submit', 'submit');
    }

    /**
     * {@inheritdoc}
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => $this->class
            ]
        );
    }
}
 

Resources/views/Message/form.html.twig
{% extends layout %}
{% trans_default_domain 'SeoSAFeedbackBundle' %}

{% block seo_sa_feedback_content %}
    <form class="seo_sa_feedback_form" action="{{ path('seo_sa_feedback_put') }}" method="POST">
        {{ form_widget(form) }}
        <input type="hidden" name="_method" value="PUT"/>
    </form>
{% endblock seo_sa_feedback_content %}

Resources/views/Message/list.html.twig
{% extends layout %}
{% trans_default_domain 'SeoSAFeedbackBundle' %}

{% block seo_sa_feedback_content %}
    {% block seo_sa_feedback_new_messages %}
        <div>
            <h2>{{ 'New messages'|trans }}</h2>
            {% include 'SeoSAFeedbackBundle:Message:list_content.html.twig' with {'messages': not_checked_messages} %}
        </div>
    {% endblock seo_sa_feedback_new_messages %}

    {% block seo_sa_feedback_old_messages %}
        <div>
            <h2>{{ 'Old messages'|trans }}</h2>
            {% include 'SeoSAFeedbackBundle:Message:list_content.html.twig' with {'messages': checked_messages} %}
        </div>
    {% endblock seo_sa_feedback_old_messages %}
{% endblock seo_sa_feedback_content %}

Resources/views/Message/list_content.html.twig
{#
 # Created by PhpStorm.
 # User: andrew
 # Date: 01.04.14
 # Time: 15:32
 # Author: Kluev Andrew
 # Contact: Kluev.Andrew@gmail.com
 #}
{% trans_default_domain 'SeoSAFeedbackBundle' %}

<table class="messages_table">
    <thead>
    <tr>
        <td>{{ 'ID'|trans }}</td>
        <td>{{ 'Title'|trans }}</td>
        <td>{{ 'Created at'|trans }}</td>
        <td></td>
    </tr>
    </thead>
    <tbody>
    {% if messages|length %}
        {% for message in messages %}
            <tr>
                <td>{{ message.id }}</td>
                <td>{{ message.title }}</td>
                <td>
                    <span class="date">{{ message.createdAt|date('Y-m-d H:i:s') }}</span>
                    {% if message is seosa_feedback_signed_message and message.author %}
                        <span class="date">{{ 'Author'|trans }}: {{ message.author }}</span>
                    {% endif %}
                </td>
                <td>

                </td>
            </tr>
        {% endfor %}
    {% else %}
        <tr>
            <td class="4">{{ 'No messages'|trans }}</td>
        </tr>
    {% endif %}
    </tbody>
</table>

Resources/views/Message/show.html.twig
{% extends layout %}
{% trans_default_domain 'SeoSAFeedbackBundle' %}

{% block seo_sa_feedback_content %}
    {% block seo_sa_feedback_message_content %}
        <div class="message">
            <h2>{{ message }}</h2>
            <table>
                <tr>
                    <td>{{ 'Title'|trans }}</td>
                    <td>{{ message.title }}</td>
                </tr>
                <tr>
                    <td>{{ 'Body'|trans }}</td>
                    <td>{{ message.body }}</td>
                </tr>
                <tr>
                    <td>{{ 'Created At'|trans }}</td>
                    <td>{{ message.createdAt|date('Y-m-d H:i:s') }}</td>
                </tr>
                <tr>
                    <td>{{ 'Permalink'|trans }}</td>
                    <td><a href="{{ message.permalink }}">{{ message.permalink }}</a></td>
                </tr>
                {% if message is seosa_feedback_signed_message and message.author %}
                    <tr>
                        <td>{{ 'Author'|trans }}</td>
                        <td>{{ message.author }}</td>
                    </tr>
                {% endif %}
                {% if not message.isRead %}
                    <tr>
                        <td colspan="2">
                            <form action="{{ path('seo_sa_feedback_patch_message_read', {'messageId': message.id }) }}" method="POST">
                                <input type="hidden" name="_method" value="PATCH"/>
                                <input type="hidden" name="state" value="1"/>
                                <input type="submit" name="submit" value="{{ 'Mark as read'|trans }}"/>
                            </form>
                        </td>
                    </tr>
                {% endif %}
            </table>
        </div>
    {% endblock seo_sa_feedback_message_content %}
{% endblock seo_sa_feedback_content %}